import { Restaurant, MenuItem } from "./types";

export const LOCAL_RESTAURANTS: Restaurant[] = [
  {
    id: "r1",
    name: "Hotel Sri Rajeshwari",
    since: "EST. 1994",
    cuisine: "North Indian, South Indian, Biryani",
    locality: "Krishnagiri Locality",
    rating: 4.4,
    delivery_time: 33,
    price_range: "₹₹",
    is_veg: false,
    offer: "FLAT ₹50 OFF",
    tags: ["biryani", "south", "north", "comfort"],
    gradient_from: "#E86A2E",
    gradient_to: "#C24A1D",
    hero_image: "/restaurants/r1.jpg",
  },
  {
    id: "r2",
    name: "Annapoorna Classic",
    since: "EST. 1988",
    cuisine: "Chinese, North Indian, South Indian, Biryani",
    locality: "Krishnagiri Locality",
    rating: 4.3,
    delivery_time: 35,
    price_range: "₹₹",
    is_veg: false,
    offer: "20% OFF UPTO ₹60",
    tags: ["chinese", "north", "south", "feast"],
    gradient_from: "#C24A1D",
    gradient_to: "#8A2B08",
    hero_image: "/restaurants/r2.jpg",
  },
  {
    id: "r3",
    name: "Srirangam Cafe",
    since: "EST. 2002",
    cuisine: "South Indian Tiffin, Filter Coffee",
    locality: "Old Bus Stand, Krishnagiri",
    rating: 4.5,
    delivery_time: 25,
    price_range: "₹",
    is_veg: true,
    offer: "PURE VEG SPECIAL",
    tags: ["south", "quick", "comfort"],
    gradient_from: "#4C7A5A",
    gradient_to: "#2E5137",
    hero_image: "/restaurants/r3.jpg",
  },
  {
    id: "r4",
    name: "Salem RR Biryani",
    since: "EST. 1998",
    cuisine: "Authentic Salem Biryani, Kebabs",
    locality: "Ramapuram, Krishnagiri",
    rating: 4.5,
    delivery_time: 30,
    price_range: "₹₹",
    is_veg: false,
    offer: "BIRYANI COMBO @ ₹249",
    tags: ["biryani", "spicy", "feast"],
    gradient_from: "#8A2B08",
    gradient_to: "#521703",
    hero_image: "/restaurants/r4.jpg",
  },
  {
    id: "r5",
    name: "Feast Pizza",
    since: "EST. 2016",
    cuisine: "Handtossed Pizza, Pasta, Garlic Bread",
    locality: "Krishnagiri Locality",
    rating: 4.3,
    delivery_time: 35,
    price_range: "₹₹",
    is_veg: false,
    offer: "BUY 1 GET 1 FREE",
    tags: ["pizza", "comfort", "quick"],
    gradient_from: "#E86A2E",
    gradient_to: "#C24A1D",
    hero_image: "/restaurants/r5.jpg",
  },
  {
    id: "r6",
    name: "Meat And Eat",
    since: "EST. 2015",
    cuisine: "Burgers, Grill, BBQ Wings",
    locality: "Rayakottai Main Road, Krishnagiri",
    rating: 4.4,
    delivery_time: 22,
    price_range: "₹₹",
    is_veg: false,
    offer: "BURGER COMBO 15% OFF",
    tags: ["grill", "spicy", "quick"],
    gradient_from: "#C24A1D",
    gradient_to: "#8A2B08",
    hero_image: "/restaurants/r6.jpg",
  },
  {
    id: "r7",
    name: "Anukrishna Sweets & Bakery",
    since: "EST. 1992",
    cuisine: "Bakery, Ghee Sweets, Savouries",
    locality: "Krishnagiri Town",
    rating: 4.6,
    delivery_time: 25,
    price_range: "₹",
    is_veg: true,
    offer: "FRESH BAKED DAILY",
    tags: ["bakery", "sweet", "quick"],
    gradient_from: "#4C7A5A",
    gradient_to: "#2E5137",
    hero_image: "/restaurants/r7.jpg",
  },
  {
    id: "r8",
    name: "Belgium Bliss Waffles",
    since: "EST. 2021",
    cuisine: "Belgian Waffles, Thick Shakes, Sundaes",
    locality: "Katiganapalli, Krishnagiri",
    rating: 4.6,
    delivery_time: 30,
    price_range: "₹₹",
    is_veg: true,
    offer: "FREE OREO SHAKE OVER ₹299",
    tags: ["sweet", "cafe", "comfort"],
    gradient_from: "#E86A2E",
    gradient_to: "#8A2B08",
    hero_image: "/restaurants/r8.jpg",
  },
  {
    id: "r9",
    name: "Hotel Saravana Bhavan",
    since: "EST. 1981",
    cuisine: "South Indian, Tiffin, Meals",
    locality: "Old Bus Stand, Krishnagiri",
    rating: 4.6,
    delivery_time: 20,
    price_range: "₹₹",
    is_veg: true,
    offer: "20% OFF UPTO ₹50",
    tags: ["south", "comfort", "quick"],
    gradient_from: "#4C7A5A",
    gradient_to: "#2E5137",
    hero_image: "/restaurants/r9.jpg",
  },
  {
    id: "r10",
    name: "Hotel Tamilnadu (TTDC)",
    since: "EST. 1978",
    cuisine: "Chettinad, South Indian, Seafood",
    locality: "Salem Main Road, Krishnagiri",
    rating: 4.2,
    delivery_time: 30,
    price_range: "₹₹₹",
    is_veg: false,
    offer: "FLAT ₹100 OFF",
    tags: ["south", "spicy", "feast"],
    gradient_from: "#C24A1D",
    gradient_to: "#8A2B08",
    hero_image: "/restaurants/r10.jpg",
  },
  {
    id: "r11",
    name: "Tibetan Momos & Chinese",
    since: "EST. 2019",
    cuisine: "Momos, Chinese, Tibetan Soups",
    locality: "Rayakottai Road, Krishnagiri",
    rating: 4.5,
    delivery_time: 25,
    price_range: "₹",
    is_veg: false,
    offer: "FREE DELIVERY",
    tags: ["chinese", "spicy", "quick"],
    gradient_from: "#E86A2E",
    gradient_to: "#B34A1B",
    hero_image: "/restaurants/r11.jpg",
  },
  {
    id: "r12",
    name: "Ambur Star Biryani",
    since: "EST. 1890",
    cuisine: "Ambur Biryani, Seeraga Samba, Starters",
    locality: "Hosur Main Road, Krishnagiri",
    rating: 4.7,
    delivery_time: 25,
    price_range: "₹₹",
    is_veg: false,
    offer: "STARTERS @ ₹99",
    tags: ["biryani", "spicy", "feast"],
    gradient_from: "#8A2B08",
    gradient_to: "#521703",
    hero_image: "/restaurants/r12.jpg",
  },
];

export const LOCAL_MENU_ITEMS: Record<string, MenuItem[]> = {
  r1: [
    { id: "chicken-biryani-0", restaurant_id: "r1", name: "Special Chicken Biryani", description: "Long grain basmati biryani cooked with tender chicken pieces & aromatic spices", price: 219, is_veg: false, category: "Biryani", image_url: "/menu/chicken-biryani-0.jpg" },
    { id: "mutton-biryani-1", restaurant_id: "r1", name: "Royal Mutton Biryani", description: "Slow-cooked mutton handi biryani served with onion raita & brinjal gravy", price: 289, is_veg: false, category: "Biryani", image_url: "/menu/mutton-biryani-1.jpg" },
    { id: "paneer-butter-masala-2", restaurant_id: "r1", name: "Paneer Butter Masala", description: "Cubes of fresh paneer simmered in rich creamy tomato cashew gravy", price: 179, is_veg: true, category: "Main Course", image_url: "/menu/paneer-butter-masala-2.jpg" },
    { id: "masala-dosa-3", restaurant_id: "r1", name: "Crispy Masala Dosa", description: "Golden crispy crepe stuffed with spiced potato masala, served with 3 chutneys", price: 89, is_veg: true, category: "South Indian", image_url: "/menu/masala-dosa-3.jpg" },
    { id: "butter-naan-4", restaurant_id: "r1", name: "Butter Naan", description: "Soft tandoor baked naan brushed with pure butter", price: 45, is_veg: true, category: "Breads", image_url: "/menu/butter-naan-4.jpg" },
    { id: "garlic-naan-r1", restaurant_id: "r1", name: "Garlic Butter Naan", description: "Tandoori naan topped with crushed roasted garlic and butter", price: 55, is_veg: true, category: "Breads", image_url: "/menu/butter-naan-4.jpg" },
    { id: "chicken-chettinad-r1", restaurant_id: "r1", name: "Chicken Chettinad Gravy", description: "Spicy Tamil Nadu style chicken cooked with roasted black pepper masala", price: 229, is_veg: false, category: "Main Course", image_url: "/menu/chettinad-chicken-curry.jpg" },
    { id: "mutton-chukka-r1", restaurant_id: "r1", name: "Mutton Chukka Fry", description: "Dry roasted tender mutton cooked with shallots, curry leaves & spices", price: 269, is_veg: false, category: "Starters", image_url: "/menu/nattu-kozhi-fry.jpg" },
    { id: "rose-milk-5", restaurant_id: "r1", name: "Chilled Rose Milk", description: "Refreshing sweet cold milk infused with natural rose syrup", price: 59, is_veg: true, category: "Drinks", image_url: "/menu/rose-milk-5.jpg" },
  ],
  r2: [
    { id: "chicken-fried-rice-0", restaurant_id: "r2", name: "Schezwan Chicken Fried Rice", description: "Wok-tossed rice with tender chicken, eggs & Schezwan sauce", price: 169, is_veg: false, category: "Chinese", image_url: "/menu/chicken-fried-rice-0.jpg" },
    { id: "gobi-manchurian-1", restaurant_id: "r2", name: "Crispy Gobi Manchurian", description: "Deep fried cauliflower florets tossed in tangy garlic soya sauce", price: 139, is_veg: true, category: "Chinese", image_url: "/menu/gobi-manchurian-1.jpg" },
    { id: "veg-biryani-2", restaurant_id: "r2", name: "Hyderabadi Veg Dum Biryani", description: "Assorted fresh vegetables & paneer dum biryani served with mirchi ka salan", price: 149, is_veg: true, category: "Biryani", image_url: "/menu/veg-biryani-2.jpg" },
    { id: "dal-makhani-3", restaurant_id: "r2", name: "Dal Makhani", description: "Black lentils slow-cooked overnight with cream & butter", price: 159, is_veg: true, category: "Main Course", image_url: "/menu/dal-makhani-3.jpg" },
    { id: "chilli-paneer-r2", restaurant_id: "r2", name: "Chilli Paneer Dry", description: "Cottage cheese cubes tossed with capsicum, onion & Szechuan peppers", price: 179, is_veg: true, category: "Chinese", image_url: "/menu/gobi-manchurian-1.jpg" },
    { id: "veg-noodles-r2", restaurant_id: "r2", name: "Veg Hakka Noodles", description: "Classic Indo-Chinese noodles wok-fried with crisp julienned vegetables", price: 139, is_veg: true, category: "Chinese", image_url: "/menu/veg-noodles-2.jpg" },
    { id: "idli-sambar-4", restaurant_id: "r2", name: "Hot Idli Sambar (2 Pcs)", description: "Steamed rice cakes served soaked in piping hot drumstick sambar", price: 69, is_veg: true, category: "South Indian", image_url: "/menu/idli-sambar-4.jpg" },
  ],
  r3: [
    { id: "masala-dosa-0", restaurant_id: "r3", name: "Srirangam Special Masala Dosa", description: "Signature thin roasted dosa with red chutney spread & potato masala", price: 79, is_veg: true, category: "South Indian", image_url: "/menu/masala-dosa-0.jpg" },
    { id: "rava-idli-1", restaurant_id: "r3", name: "Ghee Rava Idli (2 Pcs)", description: "Steamed semolina cakes tempered with cashews, mustard seeds & ghee", price: 69, is_veg: true, category: "South Indian", image_url: "/menu/rava-idli-1.jpg" },
    { id: "onion-uttapam-r3", restaurant_id: "r3", name: "Special Onion Podi Uttapam", description: "Thick savory pancake topped with caramelized onions & spicy gun powder", price: 85, is_veg: true, category: "South Indian", image_url: "/menu/masala-dosa-0.jpg" },
    { id: "medu-vada-r3", restaurant_id: "r3", name: "Medu Vada with Sambar (2 Pcs)", description: "Crispy fried lentil donuts served with spicy sambar and coconut chutney", price: 55, is_veg: true, category: "South Indian", image_url: "/menu/medu-vada-2pcs.jpg" },
    { id: "sweet-pongal-r3", restaurant_id: "r3", name: "Ghee Sakkarai Pongal", description: "Traditional sweet rice pudding made with jaggery, ghee, cashews & raisins", price: 65, is_veg: true, category: "South Indian", image_url: "/menu/rava-idli-1.jpg" },
    { id: "veg-noodles-2", restaurant_id: "r3", name: "Veg Hakka Noodles", description: "Street-style wok tossed noodles loaded with crunchy vegetables", price: 119, is_veg: true, category: "Chinese", image_url: "/menu/veg-noodles-2.jpg" },
    { id: "filter-coffee-3", restaurant_id: "r3", name: "Degree Filter Coffee", description: "Authentic South Indian chicory infused strong filter coffee", price: 39, is_veg: true, category: "Drinks", image_url: "/menu/filter-coffee-3.jpg" },
  ],
  r4: [
    { id: "chicken-biryani-0-r4", restaurant_id: "r4", name: "Salem Special Chicken Biryani", description: "Authentic Salem style spiced chicken biryani with boiled egg", price: 199, is_veg: false, category: "Biryani", image_url: "/menu/chicken-biryani-0-r4.jpg" },
    { id: "mutton-biryani-1-r4", restaurant_id: "r4", name: "Salem Mutton Biryani", description: "Tender mutton pieces cooked with short grain rice & authentic Salem masala", price: 279, is_veg: false, category: "Biryani", image_url: "/menu/mutton-biryani-1-r4.jpg" },
    { id: "chicken-65-2", restaurant_id: "r4", name: "Spicy Chicken 65", description: "Deep fried chicken chunks tossed with curry leaves & green chillies", price: 179, is_veg: false, category: "Starters", image_url: "/menu/chicken-65-2.jpg" },
    { id: "salem-fish-fry-r4", restaurant_id: "r4", name: "Salem Tawa Fish Fry", description: "Fish fillets marinated in Salem red chilli garlic paste & pan-seared", price: 210, is_veg: false, category: "Starters", image_url: "/menu/fish-head-curry.jpg" },
    { id: "egg-biryani-r4", restaurant_id: "r4", name: "Salem Egg Biryani (2 Eggs)", description: "Seeraga Samba biryani rice served with 2 hard boiled spiced eggs", price: 149, is_veg: false, category: "Biryani", image_url: "/menu/chicken-biryani-0-r4.jpg" },
    { id: "chicken-pepper-fry-r4", restaurant_id: "r4", name: "Black Pepper Chicken Fry", description: "Boneless chicken pieces sautéed with crushed black pepper & shallots", price: 199, is_veg: false, category: "Starters", image_url: "/menu/chicken-65-2.jpg" },
    { id: "plain-raita-3", restaurant_id: "r4", name: "Fresh Onion Raita", description: "Chilled whipped yogurt with diced onions, cucumber & coriander", price: 39, is_veg: true, category: "Sides", image_url: "/menu/plain-raita-3.jpg" },
  ],
  r5: [
    { id: "margherita-pizza-0", restaurant_id: "r5", name: "Classic Margherita Pizza (9-inch)", description: "Fresh mozzarella cheese, tomato sauce & organic basil", price: 199, is_veg: true, category: "Pizza", image_url: "/menu/margherita-pizza-0.jpg" },
    { id: "chicken-tikka-pizza-1", restaurant_id: "r5", name: "Chicken Tikka Feast Pizza (9-inch)", description: "Spiced chicken tikka, red paprika, onions & extra cheese", price: 289, is_veg: false, category: "Pizza", image_url: "/menu/chicken-tikka-pizza-1.jpg" },
    { id: "farmhouse-pizza-2", restaurant_id: "r5", name: "Gourmet Farmhouse Pizza (9-inch)", description: "Capsicum, mushrooms, sweet corn, tomatoes & mozzarella", price: 249, is_veg: true, category: "Pizza", image_url: "/menu/farmhouse-pizza-2.jpg" },
    { id: "pepperoni-pizza-r5", restaurant_id: "r5", name: "Smoky Chicken Pepperoni Pizza (9-inch)", description: "Sliced chicken pepperoni, black olives, jalapenos & melted mozzarella", price: 319, is_veg: false, category: "Pizza", image_url: "/menu/chicken-tikka-pizza-1.jpg" },
    { id: "alfredo-pasta-r5", restaurant_id: "r5", name: "Creamy White Sauce Alfredo Pasta", description: "Penne pasta tossed in rich butter cream garlic cheese sauce with veggies", price: 189, is_veg: true, category: "Pasta", image_url: "/menu/cheese-garlic-bread-3.jpg" },
    { id: "choco-lava-r5", restaurant_id: "r5", name: "Warm Choco Lava Cake", description: "Moist chocolate cake filled with hot molten chocolate lava", price: 99, is_veg: true, category: "Desserts", image_url: "/menu/chocolate-brownie-2.jpg" },
    { id: "cheese-garlic-bread-3", restaurant_id: "r5", name: "Stuffed Cheese Garlic Bread", description: "Freshly baked garlic bread filled with melted mozzarella & jalapeños", price: 119, is_veg: true, category: "Sides", image_url: "/menu/cheese-garlic-bread-3.jpg" },
  ],
  r6: [
    { id: "mutton-seekh-kebab-0", restaurant_id: "r6", name: "Mutton Seekh Kebab (4 Pcs)", description: "Juicy minced mutton skewers grilled over charcoal, served with mint chutney", price: 249, is_veg: false, category: "Grill", image_url: "/menu/mutton-seekh-kebab-0.jpg" },
    { id: "tandoori-chicken-half-1", restaurant_id: "r6", name: "Tandoori Chicken (Half)", description: "Chicken marinated in yogurt & red spices, roasted in clay tandoor", price: 229, is_veg: false, category: "Grill", image_url: "/menu/tandoori-chicken-half-1.jpg" },
    { id: "bbq-chicken-wings-2", restaurant_id: "r6", name: "Smoky BBQ Chicken Wings (6 Pcs)", description: "Crispy chicken wings glazed with hickory smoky BBQ sauce", price: 199, is_veg: false, category: "Grill", image_url: "/menu/bbq-chicken-wings-2.jpg" },
    { id: "paneer-tikka-3", restaurant_id: "r6", name: "Charcoal Paneer Tikka", description: "Paneer cubes marinated in tikka spices grilled with capsicum & onion", price: 189, is_veg: true, category: "Grill", image_url: "/menu/paneer-tikka-3.jpg" },
    { id: "double-burger-r6", restaurant_id: "r6", name: "Double Cheese Crispy Chicken Burger", description: "Double crispy fried chicken patty with cheddar cheese, lettuce & mayo", price: 169, is_veg: false, category: "Burgers", image_url: "/menu/bbq-chicken-wings-2.jpg" },
    { id: "peri-peri-fries-r6", restaurant_id: "r6", name: "Peri Peri French Fries (Large)", description: "Crispy potato fries dusted with spicy African peri peri seasoning", price: 99, is_veg: true, category: "Sides", image_url: "/menu/bbq-chicken-wings-2.jpg" },
  ],
  r7: [
    { id: "mysore-pak-0", restaurant_id: "r7", name: "Pure Ghee Mysore Pak (250g)", description: "Melt-in-mouth traditional South Indian sweet made with pure cow ghee & gram flour", price: 189, is_veg: true, category: "Sweets", image_url: "/menu/mysore-pak-0.jpg" },
    { id: "veg-puff-1", restaurant_id: "r7", name: "Hot Bakery Veg Puff", description: "Flaky puff pastry stuffed with spiced potato & vegetable filling", price: 25, is_veg: true, category: "Snacks", image_url: "/menu/veg-puff-1.jpg" },
    { id: "chocolate-brownie-2", restaurant_id: "r7", name: "Fudgy Chocolate Brownie", description: "Rich Belgian dark chocolate brownie topped with chocolate drizzle", price: 69, is_veg: true, category: "Bakery", image_url: "/menu/chocolate-brownie-2.jpg" },
    { id: "gulab-jamun-r7", restaurant_id: "r7", name: "Soft Gulab Jamun (4 Pcs)", description: "Traditional fried khoya dumplings soaked in cardamom sugar syrup", price: 89, is_veg: true, category: "Sweets", image_url: "/menu/mysore-pak-0.jpg" },
    { id: "rasgulla-r7", restaurant_id: "r7", name: "Sponge Rasgulla (4 Pcs)", description: "Soft spongy cottage cheese balls soaked in light sugar syrup", price: 99, is_veg: true, category: "Sweets", image_url: "/menu/mysore-pak-0.jpg" },
    { id: "black-forest-cake-r7", restaurant_id: "r7", name: "Black Forest Pastry", description: "Layers of chocolate sponge cake with fresh whipped cream & cherries", price: 75, is_veg: true, category: "Bakery", image_url: "/menu/chocolate-brownie-2.jpg" },
    { id: "rusk-toast-3", restaurant_id: "r7", name: "Butter Tea Rusk (400g)", description: "Crispy double baked tea toast rusks", price: 49, is_veg: true, category: "Bakery", image_url: "/menu/rusk-toast-3.jpg" },
  ],
  r8: [
    { id: "belgian-chocolate-waffle-0", restaurant_id: "r8", name: "Belgian Dark Chocolate Waffle", description: "Crispy warm waffle smothered with melted Belgian dark chocolate", price: 149, is_veg: true, category: "Waffles", image_url: "/menu/belgian-chocolate-waffle-0.jpg" },
    { id: "nutella-banana-waffle-1", restaurant_id: "r8", name: "Nutella Banana Waffle", description: "Fresh waffle loaded with Nutella spread & fresh banana slices", price: 169, is_veg: true, category: "Waffles", image_url: "/menu/nutella-banana-waffle-1.jpg" },
    { id: "triple-choco-waffle-r8", restaurant_id: "r8", name: "Triple Chocolate Overload Waffle", description: "Loaded with milk chocolate, dark chocolate, white chocolate & chips", price: 189, is_veg: true, category: "Waffles", image_url: "/menu/belgian-chocolate-waffle-0.jpg" },
    { id: "oreo-shake-2", restaurant_id: "r8", name: "Thick Oreo Milkshake", description: "Creamy vanilla ice cream blended with crushed Oreo cookies & chocolate fudge", price: 129, is_veg: true, category: "Shakes", image_url: "/menu/oreo-shake-2.jpg" },
    { id: "brownie-sundae-r8", restaurant_id: "r8", name: "Hot Fudge Brownie Sundae", description: "Warm chocolate brownie topped with 2 scoops of vanilla ice cream & hot fudge", price: 159, is_veg: true, category: "Desserts", image_url: "/menu/nutella-banana-waffle-1.jpg" },
    { id: "cold-coffee-r8", restaurant_id: "r8", name: "Cold Coffee with Ice Cream", description: "Chilled blended espresso coffee topped with a scoop of vanilla ice cream", price: 119, is_veg: true, category: "Shakes", image_url: "/menu/oreo-shake-2.jpg" },
    { id: "mango-lassi-3", restaurant_id: "r8", name: "Alphonso Mango Lassi", description: "Thick sweet yogurt smoothie blended with Alphonso mango pulp", price: 89, is_veg: true, category: "Drinks", image_url: "/menu/mango-lassi-3.jpg" },
  ],
  r9: [
    { id: "saravana-special-meals", restaurant_id: "r9", name: "Saravana Special South Indian Meals", description: "Banana leaf thali served with rice, sambar, vatha kuzhambu, rasam, kootu, poriyal, curd & appalam", price: 160, is_veg: true, category: "Meals", image_url: "/menu/saravana-special-meals.jpg" },
    { id: "ghee-roast-dosa", restaurant_id: "r9", name: "Special Ghee Roast Dosa", description: "Crispy paper-thin dosa made with pure cow ghee, served with coconut chutney & tiffin sambar", price: 110, is_veg: true, category: "Tiffin", image_url: "/menu/ghee-roast-dosa.jpg" },
    { id: "medu-vada-2pcs", restaurant_id: "r9", name: "Crispy Medu Vada (2 Pcs)", description: "Golden urad dal fritters served piping hot with coconut & tomato chutney", price: 55, is_veg: true, category: "Tiffin", image_url: "/menu/medu-vada-2pcs.jpg" },
    { id: "mini-tiffin-combo", restaurant_id: "r9", name: "Saravana Mini Tiffin Combo", description: "Mini Dosa, Idli (1 pc), Vada (1 pc), Rava Kesari & Filter Coffee combo", price: 145, is_veg: true, category: "Combos", image_url: "/menu/mini-tiffin-combo.jpg" },
    { id: "poori-masala-2pcs", restaurant_id: "r9", name: "Poori Masala (2 Pcs)", description: "Fluffy whole wheat pooris served with spiced potato onion masala", price: 75, is_veg: true, category: "Tiffin", image_url: "/menu/poori-masala-2pcs.jpg" },
    { id: "rava-kesari-r9", restaurant_id: "r9", name: "Ghee Rava Kesari", description: "Traditional sweet semolina pudding garnished with ghee roasted cashews & cardamom", price: 65, is_veg: true, category: "Desserts", image_url: "/menu/mini-tiffin-combo.jpg" },
    { id: "sambar-vada-r9", restaurant_id: "r9", name: "Sambar Vada (2 Pcs)", description: "Lentil vadas soaked in hot fragrant drumstick sambar garnished with ghee", price: 65, is_veg: true, category: "Tiffin", image_url: "/menu/medu-vada-2pcs.jpg" },
  ],
  r10: [
    { id: "chettinad-chicken-curry", restaurant_id: "r10", name: "Authentic Chettinad Chicken Curry", description: "Farm chicken cooked with freshly ground roasted pepper, fennel, kalpasi & shallots", price: 240, is_veg: false, category: "Main Course", image_url: "/menu/chettinad-chicken-curry.jpg" },
    { id: "nattu-kozhi-fry", restaurant_id: "r10", name: "Nattu Kozhi Fry (Country Chicken)", description: "Country chicken pan-fried with shallots, curry leaves & crushed black pepper", price: 270, is_veg: false, category: "Starters", image_url: "/menu/nattu-kozhi-fry.jpg" },
    { id: "fish-head-curry", restaurant_id: "r10", name: "Krishnagiri Dam Fish Curry", description: "Fresh river fish cooked in tangy tamarind coconut gravy with green chillies", price: 230, is_veg: false, category: "Main Course", image_url: "/menu/fish-head-curry.jpg" },
    { id: "south-indian-nonveg-meals", restaurant_id: "r10", name: "Chettinad Non-Veg Meals", description: "Rice, Chicken Gravy, Mutton Salan, Fish Curry, Rasam, Curd & Sweet", price: 220, is_veg: false, category: "Meals", image_url: "/menu/south-indian-nonveg-meals.jpg" },
    { id: "mutton-chukka-r10", restaurant_id: "r10", name: "Mutton Chukka Varuval", description: "Tender goat meat slow roasted with Chettinad whole spices and shallots", price: 290, is_veg: false, category: "Starters", image_url: "/menu/nattu-kozhi-fry.jpg" },
    { id: "crab-masala-r10", restaurant_id: "r10", name: "Spicy Chettinad Crab Masala", description: "Fresh crab cooked in aromatic spicy black pepper onion tomato gravy", price: 320, is_veg: false, category: "Main Course", image_url: "/menu/fish-head-curry.jpg" },
    { id: "malabar-parotta-r10", restaurant_id: "r10", name: "Flaky Malabar Parotta (2 Pcs)", description: "Layered flaky maida parotta hot off the tawa", price: 50, is_veg: true, category: "Breads", image_url: "/menu/ghee-roast-dosa.jpg" },
  ],
  r11: [
    { id: "steamed-chicken-momos-8pcs", restaurant_id: "r11", name: "Steamed Chicken Momos (8 Pcs)", description: "Juicy minced chicken dumplings wrapped thin, served with spicy garlic tomato chutney", price: 130, is_veg: false, category: "Momos", image_url: "/menu/steamed-chicken-momos-8pcs.jpg" },
    { id: "fried-veg-momos-8pcs", restaurant_id: "r11", name: "Crispy Fried Veg Momos (8 Pcs)", description: "Crispy deep-fried vegetable dumplings stuffed with cabbage, carrot & cheese", price: 110, is_veg: true, category: "Momos", image_url: "/menu/fried-veg-momos-8pcs.jpg" },
    { id: "cheese-momos-r11", restaurant_id: "r11", name: "Cheese & Corn Steam Momos (8 Pcs)", description: "Steamed dumplings packed with molten mozzarella, sweet corn & herbs", price: 140, is_veg: true, category: "Momos", image_url: "/menu/steamed-chicken-momos-8pcs.jpg" },
    { id: "chicken-thukpa-soup", restaurant_id: "r11", name: "Tibetan Chicken Thukpa Soup", description: "Hearty noodle soup with shredded chicken, spring onions & Tibetan aromatic spices", price: 150, is_veg: false, category: "Soups", image_url: "/menu/chicken-thukpa-soup.jpg" },
    { id: "chilli-chicken-dry", restaurant_id: "r11", name: "Indo-Chinese Chilli Chicken (Dry)", description: "Crispy fried chicken tossed with capsicum, onions, soy sauce & green chillies", price: 180, is_veg: false, category: "Chinese", image_url: "/menu/chilli-chicken-dry.jpg" },
    { id: "schezwan-noodles-r11", restaurant_id: "r11", name: "Spicy Schezwan Veg Noodles", description: "Wok tossed noodles in fiery home-style Schezwan chilli garlic sauce", price: 135, is_veg: true, category: "Chinese", image_url: "/menu/chicken-thukpa-soup.jpg" },
    { id: "manchow-soup-r11", restaurant_id: "r11", name: "Chicken Manchow Soup with Fried Noodles", description: "Thick hot and sour chicken soup garnished with crispy fried noodles", price: 120, is_veg: false, category: "Soups", image_url: "/menu/chicken-thukpa-soup.jpg" },
  ],
  r12: [
    { id: "ambur-mutton-biryani", restaurant_id: "r12", name: "Ambur Star Mutton Biryani", description: "Authentic Seeraga Samba rice biryani cooked with tender mutton chunks & red chilli paste", price: 290, is_veg: false, category: "Biryani", image_url: "/menu/ambur-mutton-biryani.jpg" },
    { id: "ambur-chicken-biryani", restaurant_id: "r12", name: "Ambur Star Chicken Biryani", description: "Traditional Ambur style chicken biryani served with brinjal pachadi & onion raita", price: 210, is_veg: false, category: "Biryani", image_url: "/menu/ambur-chicken-biryani.jpg" },
    { id: "chicken-pakoda-200g", restaurant_id: "r12", name: "Crispy Chicken Pakoda (200g)", description: "Boneless chicken bites marinated in spices & fried crisp with curry leaves", price: 160, is_veg: false, category: "Starters", image_url: "/menu/chicken-pakoda-200g.jpg" },
    { id: "ambur-mutton-chukka-r12", restaurant_id: "r12", name: "Ambur Style Mutton Chukka", description: "Tender goat meat sautéed with hand-ground spices and caramelized shallots", price: 280, is_veg: false, category: "Starters", image_url: "/menu/ambur-mutton-biryani.jpg" },
    { id: "chicken-65-r12", restaurant_id: "r12", name: "Ambur Chicken 65 (Boneless)", description: "Deep-fried spicy boneless chicken nuggets with curry leaf garlic seasoning", price: 185, is_veg: false, category: "Starters", image_url: "/menu/chicken-pakoda-200g.jpg" },
    { id: "plain-kuska-r12", restaurant_id: "r12", name: "Seeraga Samba Plain Kuska Biryani Rice", description: "Fragrant biryani rice cooked in chicken broth without meat pieces", price: 120, is_veg: false, category: "Biryani", image_url: "/menu/ambur-chicken-biryani.jpg" },
    { id: "brinjal-khatte-salan", restaurant_id: "r12", name: "Ambur Ennai Kathirikai Salan", description: "Tangy brinjal gravy cooked with sesame, peanut & tamarind — perfect biryani accompaniment", price: 70, is_veg: true, category: "Sides", image_url: "/menu/brinjal-khatte-salan.jpg" },
  ],
};
