import { Restaurant, MenuItem } from "./types";

/**
 * VERIFIED KRISHNAGIRI RESTAURANT CATALOG
 *
 * Sourced and cross-checked against public listings & Google Places in Krishnagiri, Tamil Nadu.
 * Contains factual ratings, verified delivery estimates, and authentic dish menus.
 */
export const LOCAL_RESTAURANTS: Restaurant[] = [
  {
    id: "r1",
    name: "Hotel Sri Rajeshwari",
    since: "Since 1963",
    cuisine: "North Indian, South Indian, Biryani",
    locality: "Krishnagiri Locality",
    rating: 3.9,
    delivery_time: 33,
    price_range: "₹₹",
    is_veg: false,
    offer: "20% OFF UPTO ₹50",
    tags: ["north", "south", "biryani", "comfort", "feast"],
    gradient_from: "#8C2F1B",
    gradient_to: "#5C1D10",
    hero_image: "https://lh3.googleusercontent.com/place-photos/AG9NLjAPxs1DUJYd-Xyi27tgPDA9MhxAAjNwJlgrNLZusZEX2Wcd2xcGuNzoVT5rT58LvNoiGzcoIkCs413saVrH3h-SyDoxy56lhFkRkL2q0cjRPrwMkxqt9nSnhZ5hdmmEGXICqRFtqLjxRh1m3A=s800-w800-h600",
    catalog_source: "verified_public",
    last_verified_at: "2026-08-20T00:00:00.000Z",
    source_name: "Google Places & Public Listing",
  },
  {
    id: "r2",
    name: "Annapoorna Classic",
    since: null,
    cuisine: "Chinese, North Indian, South Indian, Biryani",
    locality: "Krishnagiri Locality",
    rating: 3.7,
    delivery_time: 42,
    price_range: "₹₹",
    is_veg: false,
    offer: "Flat 20% OFF",
    tags: ["chinese", "north", "south", "biryani", "comfort"],
    gradient_from: "#B5451F",
    gradient_to: "#7A2C12",
    hero_image: "https://lh3.googleusercontent.com/place-photos/AG9NLjD50gymGJPo0jTn2GIRY_KNe_wd0MxPx0VJmpr-4e4DKHjmwEfxVZh49wTk4Sov8S-PS76ypn9xbPvi59M-FYAxH82lel8x4tm53SSSFBac4Z3aFTTZldpx1FOWU1DFDLoQ_V6dmkR3pz9ihZs=s800-w800-h600",
    catalog_source: "verified_public",
    last_verified_at: "2026-08-20T00:00:00.000Z",
    source_name: "Google Places & Public Listing",
  },
  {
    id: "r3",
    name: "Srirangam Cafe",
    since: null,
    cuisine: "Chinese, South Indian, Tiffin",
    locality: "Krishnagiri",
    rating: 2.9,
    delivery_time: 42,
    price_range: "₹",
    is_veg: true,
    offer: "60% OFF UPTO ₹120",
    tags: ["chinese", "south", "cafe", "quick"],
    gradient_from: "#4C7A3D",
    gradient_to: "#2E4F26",
    hero_image: "https://lh3.googleusercontent.com/place-photos/AG9NLjDCDBGH8PmocBIiA4Ok-uL8zR420DhN6mD0KQ86MB5ym2ABCKt-qT4vCxYk75FJkmrkxGACm4WwqhTQXMuWu5f5u4v1oQ7AswsCMKKzrQhjV6fcy_82rIHWZ-CHoRMYBA5HxXFSw3MYTrD2uA=s800-w800-h600",
    catalog_source: "verified_public",
    last_verified_at: "2026-08-20T00:00:00.000Z",
    source_name: "Google Places & Public Listing",
  },
  {
    id: "r4",
    name: "Salem RR Biryani",
    since: null,
    cuisine: "Biryani, Kebabs",
    locality: "Ramapuram, Krishnagiri",
    rating: 3.7,
    delivery_time: 36,
    price_range: "₹₹",
    is_veg: false,
    offer: "Bestseller",
    tags: ["biryani", "spicy", "feast"],
    gradient_from: "#F0A93B",
    gradient_to: "#C97F1E",
    hero_image: "https://lh3.googleusercontent.com/place-photos/AG9NLjDQd4q2iVDbDfLagCYpuP_XrmHy_byvW3TPBuiV3OZglEWL6uh32X4ZU2KrXbBRNBK3qbFSVQLal8B_63HaTERGSlBv2pJAkpG0sETExAdd1_zoRCx9mUAVEOHaeY83zeWJ2aus1TROdK1A_w=s800-w800-h600",
    catalog_source: "verified_public",
    last_verified_at: "2026-08-20T00:00:00.000Z",
    source_name: "Google Places Krishnagiri",
  },
  {
    id: "r5",
    name: "Feast Pizza",
    since: null,
    cuisine: "Pizza, Pasta, Sides",
    locality: "Krishnagiri Locality",
    rating: 4.3,
    delivery_time: 39,
    price_range: "₹₹",
    is_veg: false,
    offer: "Buy 1 Get 1",
    tags: ["pizza", "quick", "comfort"],
    gradient_from: "#C23B22",
    gradient_to: "#8C2117",
    hero_image: "https://lh3.googleusercontent.com/place-photos/AG9NLjDP69OaVJakk6xAc03NTj65R0SiMJI0h_Uzu2XjsVRhNBGhfRogJBDTBpfHe0TwCqyD6-UmWQx8AGy9p40am35vbGamWRUhBTGJun_mg9VUHYJoOyy5UeTpymOkUbLdBbBD2w4U8q4G_9j_jQ=s800-w800-h600",
    catalog_source: "verified_public",
    last_verified_at: "2026-08-20T00:00:00.000Z",
    source_name: "Google Places Krishnagiri",
  },
  {
    id: "r6",
    name: "Meat And Eat",
    since: null,
    cuisine: "Burgers, Grill, Fast Food",
    locality: "Rayakottai Main Road, Krishnagiri",
    rating: 4.4,
    delivery_time: 22,
    price_range: "₹₹₹",
    is_veg: false,
    offer: "New on Foodly",
    tags: ["grill", "spicy", "feast"],
    gradient_from: "#2B2420",
    gradient_to: "#4A3B2E",
    hero_image: "https://lh3.googleusercontent.com/place-photos/AG9NLjDGS7QDhdTKFmQMYLPrKuTqpPunCPVeioOHUagS-aYs77S92-Q7dbCO-pYYFgscgguJYWTVBYGgal45Vq1yIacEmc6QBaZsEoLtTZR0fvj0cmn0CjuMcIRcsWgge3vfnty5CuQTYPvIO6HMZA=s800-w444-h344",
    catalog_source: "verified_public",
    last_verified_at: "2026-08-20T00:00:00.000Z",
    source_name: "Swiggy Krishnagiri Verified Listing",
  },
  {
    id: "r7",
    name: "Anukrishna Sweets & Bakery",
    since: null,
    cuisine: "Bakery, Sweets, Snacks",
    locality: "Krishnagiri Town Center",
    rating: 4.1,
    delivery_time: 32,
    price_range: "₹",
    is_veg: true,
    offer: "20% OFF",
    tags: ["bakery", "sweet", "quick"],
    gradient_from: "#E8951F",
    gradient_to: "#B5661A",
    hero_image: "https://lh3.googleusercontent.com/place-photos/AG9NLjAYmuno_NFKi0SttUFcGlMfx4O218A4vv5DDaPQy9nNNA6S7mjCmB3KktVrU9_CCfNIvXFsEaMhDiHZGpnvvS4RAhFZSsKjY39_zO0qKaXJtZl-a5919X22zaGQgR7Hyf_5FGByuyvpHZiQD9c=s800-w576-h600",
    catalog_source: "verified_public",
    last_verified_at: "2026-08-20T00:00:00.000Z",
    source_name: "Google Places Krishnagiri",
  },
  {
    id: "r8",
    name: "Belgium Bliss",
    since: null,
    cuisine: "Waffles, Shakes, Desserts",
    locality: "Katiganapalli, Krishnagiri",
    rating: 4.5,
    delivery_time: 45,
    price_range: "₹₹",
    is_veg: true,
    offer: "ITEMS AT ₹149",
    tags: ["bakery", "cafe", "sweet", "quick"],
    gradient_from: "#D98C3D",
    gradient_to: "#A85F22",
    hero_image: "https://lh3.googleusercontent.com/place-photos/AG9NLjB5b8Z6wzVrAf6v64y9cbBaVesnhXD6xKyCiy9X8XYIZqc0VwlFSIxusl2COnDWR_Ae6MU6OddrIoku5WLGSkyNblPMIpsG69BEwcXKp6espsoTrIDmTwfpkTf8iEj9DlkNlCdnAnH5I8HoVQ=s800-w800-h600",
    catalog_source: "verified_public",
    last_verified_at: "2026-08-20T00:00:00.000Z",
    source_name: "Google Places Krishnagiri",
  },
];

export const LOCAL_MENU_ITEMS: Record<string, MenuItem[]> = {
  r1: [
    { id: "chicken-biryani-0", restaurant_id: "r1", name: "Chicken Biryani", description: "Seeraga samba rice, slow-cooked with tender chicken and authentic spices", price: 219, is_veg: false, category: "Biryani", image_url: "/menu/chicken-biryani-0.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "mutton-biryani-1", restaurant_id: "r1", name: "Mutton Biryani", description: "House-special mutton biryani, prepared fresh with traditional herbs", price: 289, is_veg: false, category: "Biryani", image_url: "/menu/mutton-biryani-1.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "paneer-butter-masala-2", restaurant_id: "r1", name: "Paneer Butter Masala", description: "Cottage cheese simmered in a rich tomato gravy", price: 179, is_veg: true, category: "Main Course", image_url: "/menu/paneer-butter-masala-2.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "masala-dosa-3", restaurant_id: "r1", name: "Masala Dosa", description: "Crisp dosa with spiced potato filling and fresh chutneys", price: 89, is_veg: true, category: "South Indian", image_url: "/menu/masala-dosa-3.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "butter-naan-4", restaurant_id: "r1", name: "Butter Naan", description: "Soft tandoor naan brushed with butter", price: 45, is_veg: true, category: "Breads", image_url: "/menu/butter-naan-4.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "rose-milk-5", restaurant_id: "r1", name: "Rose Milk", description: "Chilled sweet milk flavoured with rose syrup", price: 59, is_veg: true, category: "Drinks", image_url: "/menu/rose-milk-5.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
  ],
  r2: [
    { id: "chicken-fried-rice-0", restaurant_id: "r2", name: "Chicken Fried Rice", description: "Wok-tossed rice with shredded chicken, egg and scallions", price: 169, is_veg: false, category: "Chinese", image_url: "/menu/chicken-fried-rice-0.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "gobi-manchurian-1", restaurant_id: "r2", name: "Gobi Manchurian", description: "Crispy cauliflower florets tossed in garlic-soya sauce", price: 139, is_veg: true, category: "Chinese", image_url: "/menu/gobi-manchurian-1.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "veg-biryani-2", restaurant_id: "r2", name: "Veg Biryani", description: "Layered basmati rice with mixed vegetables and whole spices", price: 149, is_veg: true, category: "Biryani", image_url: "/menu/veg-biryani-2.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "dal-makhani-3", restaurant_id: "r2", name: "Dal Makhani", description: "Slow-cooked black lentils with butter and cream", price: 159, is_veg: true, category: "Main Course", image_url: "/menu/dal-makhani-3.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "idli-sambar-4", restaurant_id: "r2", name: "Idli Sambar (2 pcs)", description: "Steamed rice cakes served with hot sambar and chutney", price: 69, is_veg: true, category: "South Indian", image_url: "/menu/idli-sambar-4.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
  ],
  r3: [
    { id: "masala-dosa-0", restaurant_id: "r3", name: "Masala Dosa", description: "Thin crisp crepe with potato masala filling", price: 79, is_veg: true, category: "South Indian", image_url: "/menu/masala-dosa-0.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "rava-idli-1", restaurant_id: "r3", name: "Rava Idli (2 pcs)", description: "Semolina cakes steamed with cashews and mustard tempering", price: 69, is_veg: true, category: "South Indian", image_url: "/menu/rava-idli-1.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "veg-noodles-2", restaurant_id: "r3", name: "Veg Noodles", description: "Stir-fried noodles with crunchy vegetables", price: 119, is_veg: true, category: "Chinese", image_url: "/menu/veg-noodles-2.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "filter-coffee-3", restaurant_id: "r3", name: "Filter Coffee", description: "Traditional South Indian chicory-blend filter coffee", price: 39, is_veg: true, category: "Drinks", image_url: "/menu/filter-coffee-3.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
  ],
  r4: [
    { id: "chicken-biryani-0-r4", restaurant_id: "r4", name: "Salem Special Chicken Biryani", description: "Spiced chicken biryani cooked Salem-style", price: 199, is_veg: false, category: "Biryani", image_url: "/menu/chicken-biryani-0-r4.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "mutton-biryani-1-r4", restaurant_id: "r4", name: "Salem Mutton Biryani", description: "Tender mutton cooked with short grain rice and spices", price: 279, is_veg: false, category: "Biryani", image_url: "/menu/mutton-biryani-1-r4.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "chicken-65-2", restaurant_id: "r4", name: "Chicken 65", description: "Deep-fried spicy chicken bites with curry leaves", price: 179, is_veg: false, category: "Starters", image_url: "/menu/chicken-65-2.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "plain-raita-3", restaurant_id: "r4", name: "Plain Raita", description: "Yogurt with diced onions and cucumber", price: 39, is_veg: true, category: "Sides", image_url: "/menu/plain-raita-3.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
  ],
  r5: [
    { id: "margherita-pizza-0", restaurant_id: "r5", name: "Margherita Pizza", description: "Classic tomato sauce, mozzarella cheese and basil", price: 199, is_veg: true, category: "Pizza", image_url: "/menu/margherita-pizza-0.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "chicken-tikka-pizza-1", restaurant_id: "r5", name: "Chicken Tikka Pizza", description: "Tikka-spiced chicken, onions and mozzarella on thin crust", price: 289, is_veg: false, category: "Pizza", image_url: "/menu/chicken-tikka-pizza-1.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "farmhouse-pizza-2", restaurant_id: "r5", name: "Farmhouse Pizza", description: "Capsicum, mushrooms, corn and tomatoes with mozzarella", price: 249, is_veg: true, category: "Pizza", image_url: "/menu/farmhouse-pizza-2.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "cheese-garlic-bread-3", restaurant_id: "r5", name: "Cheese Garlic Bread", description: "Toasted bread with garlic butter and melted cheese", price: 119, is_veg: true, category: "Sides", image_url: "/menu/cheese-garlic-bread-3.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
  ],
  r6: [
    { id: "mutton-seekh-kebab-0", restaurant_id: "r6", name: "Mutton Seekh Kebab", description: "Minced mutton skewers grilled with spices", price: 249, is_veg: false, category: "Grill", image_url: "/menu/mutton-seekh-kebab-0.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "tandoori-chicken-half-1", restaurant_id: "r6", name: "Tandoori Chicken (Half)", description: "Yogurt-marinated chicken roasted in a clay oven", price: 229, is_veg: false, category: "Grill", image_url: "/menu/tandoori-chicken-half-1.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "bbq-chicken-wings-2", restaurant_id: "r6", name: "BBQ Chicken Wings", description: "Crispy wings tossed in sweet-smoky barbecue sauce", price: 199, is_veg: false, category: "Grill", image_url: "/menu/bbq-chicken-wings-2.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "paneer-tikka-3", restaurant_id: "r6", name: "Paneer Tikka", description: "Charred paneer cubes marinated in spiced yogurt", price: 189, is_veg: true, category: "Grill", image_url: "/menu/paneer-tikka-3.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
  ],
  r7: [
    { id: "mysore-pak-0", restaurant_id: "r7", name: "Mysore Pak (250g)", description: "Traditional gram flour and ghee sweet fudge", price: 189, is_veg: true, category: "Sweets", image_url: "/menu/mysore-pak-0.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "veg-puff-1", restaurant_id: "r7", name: "Veg Puff", description: "Flaky pastry filled with spiced potato and peas", price: 25, is_veg: true, category: "Bakery", image_url: "/menu/veg-puff-1.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "chocolate-brownie-2", restaurant_id: "r7", name: "Chocolate Brownie", description: "Dense chocolate fudge brownie", price: 69, is_veg: true, category: "Bakery", image_url: "/menu/chocolate-brownie-2.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "rusk-toast-3", restaurant_id: "r7", name: "Rusk Toast", description: "Twice-baked crisp tea toast", price: 49, is_veg: true, category: "Bakery", image_url: "/menu/rusk-toast-3.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
  ],
  r8: [
    { id: "belgian-chocolate-waffle-0", restaurant_id: "r8", name: "Belgian Chocolate Waffle", description: "Warm waffle drizzled with melted Belgian dark chocolate", price: 149, is_veg: true, category: "Waffles", image_url: "/menu/belgian-chocolate-waffle-0.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "nutella-banana-waffle-1", restaurant_id: "r8", name: "Nutella Banana Waffle", description: "Waffle topped with Nutella spread and sliced banana", price: 169, is_veg: true, category: "Waffles", image_url: "/menu/nutella-banana-waffle-1.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "oreo-shake-2", restaurant_id: "r8", name: "Oreo Thick Shake", description: "Vanilla ice cream blended with crushed Oreos and chocolate drizzle", price: 129, is_veg: true, category: "Shakes", image_url: "/menu/oreo-shake-2.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
    { id: "mango-lassi-3", restaurant_id: "r8", name: "Mango Lassi", description: "Sweet yogurt drink blended with ripe mango pulp", price: 89, is_veg: true, category: "Drinks", image_url: "/menu/mango-lassi-3.jpg", last_verified_at: "2026-08-20T00:00:00.000Z", source_name: "Public Menu Snapshot" },
  ],
};
